name: Keep draw.io export synchronized
on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yml
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: rm -rf export
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export drawio files to .pdf
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: pdf
          remove-page-suffix: true
      - name: Export drawio files to .jpg
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: jpg
          remove-page-suffix: true
          quality: 100
      - name: Export drawio files to .png
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          remove-page-suffix: true
          transparent: true
      - name: Export drawio files to .svg
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          remove-page-suffix: true
      - shell: bash
        run: curl -w "\n" -s -X PURGE https://camo.githubusercontent.com/shun-ueda/lehigh-steam-tunnel/main/export/diagram.svg
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "me@shu.nu"
          git config --global user.name "shun-ueda"
          git add -A
          git commit -m "[Actions] Sync diagram" || exit 0
          git push